### ISSUE TITLE
Attribute names in ER and table schemas should begin with upper case (W)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#140]
Unlike variable names in code, attribute names in ER and table schemas should begin with upper case. 
See discussion in PR #139 for examples.

A proposal on disposing this issue: 
- No one person can fix this issue due its nature, Rather, anyone who touches any file should address this issue.
- All future development should comply with this requirement
- All reviews should factor in this requirement
- This issue should be closed at end of M2, because incorrect use of case should be covered in individual PRs

At a higher level, a guidelines of sorts should be developed, probably for all DASSL work not just ClassDB.

Please opine.

**Comment by KevinKelly25** [comment]
As I stated in PR #139 I agree with making attribute names in ER and table schemas begin with an uppercase letter. 

As @smurthys  stated, It would make sense if any file we modify from this point on, if we all agree, should be updated to this new standard. Then before M2 is completed we should go through all files to make sure they are all up to standard.

I agree with @smurthys that we should adopt a consistent guidelines for all of DASSLE but if we do want to make guidelines before M2 it would probably be better if we discuss and attempt to solidify them by the end of today's meeting so that our work towards M2 can encompass those guidelines.

**Comment by smurthys** [comment]
I believe this issue can now be closed.
