### ISSUE TITLE
Error importing connection log (W)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#200]
Executing  `select * from classdb.importconnectionlog();` on the CS205 DB in production failed, and produced the following error message:

BTW, the IP address of the host has changed over time, but that should not cause the error reported.

```
ERROR:  could not open file "/opt/postgresql/data/logs/pg96/postgresql-03.04.csv" for reading: No such file or directory
CONTEXT:  SQL statement "COPY classdb.postgresLog FROM '/opt/postgresql/data/logs/pg96/postgresql-03.04.csv' WITH csv"
```
![image](https://user-images.githubusercontent.com/29356581/38097560-b563f4be-3343-11e8-9c89-e9568e22e603.png)

**Comment by smurthys** [comment]
IMPORTANT: For security sake, please be careful including details of the server or the DB in this thread, because the issue is about a system in production.

**Comment by KevinKelly25** [comment]
I am not sure exactly what happened with the server earlier this semester but when the server went down could the CSV file have gotten deleted, renamed, or the path changed?

**Comment by srrollo** [comment]
This issue should probably be kept open - `classdb.importconnectionlog()` should have some sort of error handling added to deal with this situation.

**Comment by srrollo** [comment]
I was able to log onto the server and confirm that only the 03-04 log file is missing. This is causing the import error. The solution outlined in the above comments still holds.

**Comment by srrollo** [comment]
The issue on the local server has been fixed by "patching" the log files.  
For future reference, I have two general ideas for approaching the code patch:    

- Check if log files exist before trying to import
- Use exception handling to catch the error when importing a missing file

The first is not possible without using a scripting language function, I need to do more research on the second to see if the file read error is handleable.

**Comment by srrollo** [comment]
PL\pgSQL does support exception handling (see [here](https://www.postgresql.org/docs/10/static/plpgsql-control-structures.html#PLPGSQL-ERROR-TRAPPING) and [here](https://www.postgresql.org/docs/10/static/errcodes-appendix.html)).  
I have used this to add some simple exception handling to `ClassDB.importConnectionLog()` that solves the issue described in this thread by skipping missing log files. See [here](https://github.com/DASSL/ClassDB/compare/log-exception-handling) for a diff. I think there are a few points to consider with how missing log files should be handled:
- Should they be skipped silently or display a message
- Should `ClassDB.importConnectionLog()` still fail but with a more descriptive error message
- Should there be a manual override parameter to skip missing log files

Any input would be appreciated.

**Comment by afig** [comment]
Apologies for not mentioning earlier that PL/pgSQL does in fact has support for exception handling (I wrote that section in the paper after all).

If we opt for failing, then we would definitely need an (easy) override, since it should be possible to have days without logs. (Consider a situation where ClassDB is deployed on a computer that is not on every day.)

I think displaying a message would be appropriate, probably at the ```NOTICE``` level. That way persons importing the log will be alerted to the fact that there are missing logs, but it does not inconvenience anyone who expects there to be days missing.

**Comment by srrollo** [comment]
No problem, my main concern was if there was a specific exception for file not found. I think the current issue with only display a notice is that it is currently not possible to go back and re-import logs from missed dates, should they be available. Although I'm not sure if this is likely to happen. It may be best to document this limitation for now.

As mentioned in #203, I think it would be a good idea to also check for `logging_collector` at the beginning of `ClassDB.importConnectionLog()`. `logging_collector` = `off` would raise a `NOTICE` as well, because it is possible there are remaining logs that need to be imported, and the exception handling will notify the user of any missing files.

**Comment by smurthys** [comment]
I have the following thoughts about `ClassDB.importConnectionLog()`:

* Work normally and then raise a notice each if `logging_collector` or `log_connections` is off
* Return a table with three attributes with one row for each date it attempts to process: date, number of activity rows added to the ClassDB log, and a `VARCHAR` remark which can for now just be the exception string if there was an exception processing a file.
* Also raise a warning with each exception encountered when processing a file

**PS:** We already have exception handling in production. See function [classDB.grantRole](https://github.com/DASSL/ClassDB/blob/14eb33909f670c0689a791e32dbd4bd3cd596784/src/db/core/addHelpersCore.sql#L323-L342)

**Comment by srrollo** [comment]
[`log-exception-handling`](https://github.com/DASSL/ClassDB/compare/log-exception-handling) now contains much of the discussed functionality.
