### ISSUE TITLE
Reading classDB.Student returns timestamps in UTC (M)

### ISSUE THREAD

**Issue by smurthys** [DASSL/ClassDB#48]
Storing timestamps in UTC is the right thing to do, but it is typical for systems to return timestamps in "local timezone"

Perhaps a function such as `getStudents(optional timezone)`: will perform `SELECT *` on the table but convert timestamps to the specified timezone or to "local" timezone if parameter is missing.

Developing a view is an alternative, but views cannot be parameterized. A view that reuses the aforementioned function to always apply the local timezone is an option. However, a view seems redundant if a function is available.

**Comment by smurthys** [comment]
I propose implementing a function. This function should be in the `ClassDB` schema and be accessible to instructors and db managers.

Design questions/considerations:
- Which script file will this and other such helpful functions be placed in? 
- Where in the installation process do these functions fit?
- What is the impact of these functions on uninstallation?

**Comment by smurthys** [comment]
Any views/functions defined to return activity information should also return date/time in local time zone with the option to convert to a specific time zone (because the server's time zone might not be the user's time zone)

**Comment by afig** [comment]
I agree that using a function to handle this is the best option. 

Currently, it seems like it would be best to implement this in the [`addHelpers.sql` script](https://github.com/DASSL/ClassDB/blob/master/src/addHelpers.sql), and handle installation/uninstallation in a manner identical to the other helper functions. 

It seems like using the `pg_timezone_abbrevs` system table to would be easiest to implement, though it would make the implementation non-portable. Since there is no equivalent `INFORMATION_SCHEMA` table available, the only other option seems to be to implement our own table that holds time zones, which would be impractical. Other helper functions in `addHelpers.sql` also use Postgres' system catalogs, so it would still be consistent with other functions in that script.

I will look into the possibility of automatically obtaining the local time zone.

**Comment by smurthys** [comment]
I agree a function can work. Specifically, functions which return time stamps should take optional user name (all users if missing) and optional format string. All users is the default if user name is missing; `'YYYY-MM-DD HH24:MI:SS TZ'` is default if format is missing. 

The advantage of the default format string is that it does not require us to know the server's time zone. However, if we need to know the server's time zone, the following query suffices: 
```sql
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'TZ');
```
Also, this [Stack Overflow thread](https://stackoverflow.com/questions/10797720/postgresql-how-to-render-date-in-different-time-zone) has some related and useful information.   

This issue is related to #134. I propose we use the checklist there to complete this work. We can close this issue when #134 is closed.

**Comment by srrollo** [comment]
Fixed in #152
